
    classDiagram
        class Calculator{
            +str binary1
            +str binary2
            +__init__(binary1: str, binary2: str)
            +add(): str
            +subtract(): str
            +multiply(): str
            +divide(): str
        }
    